version: '3'
services:
  web:
    image: osiolabs/drupaldevwithdocker-php:7.4
    ports:
      - "8002:80"
    volumes:
      - ./docroot:/var/www:cached
    environment:
      APACHE_DOCROOT_DIR: /var/www/web
    
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./db-backups:/var/mysql/backups:delegated
    environment:
      MYSQL_ROOT_PASSWORD: myroot
      MYSQL_DATABASE: drupaltest
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: secret
    
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: myroot
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G 

